### ISSUE TITLE
Recommended Websites

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#1]
When you click on the link for this website it doesn't open another tab like all of the other website links do. Not sure wh/not that matters? 
<img width="759" alt="Screen Shot 2020-04-02 at 12 22 48 PM" src="https://user-images.githubusercontent.com/19825720/78273431-d1d13f80-74dc-11ea-800e-3bb8f49b41cb.png">

**Comment by sarahlydic** [comment]
Fixed -- Checked "open in new window"
