### ISSUE TITLE
List of PD elements - only 6

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#12]
Bullets separate "Specific" from "Articulated Objectives"

![Screenshot_20200410-082840](https://user-images.githubusercontent.com/19825720/78997938-8db1f080-7b15-11ea-9317-b44e2d9e683b.png)

**Comment by sarahlydic** [comment]
@ajp9e Can you add the link to this page? Thank you!

**Comment by castl350** [comment]
@sarahlydic 
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/how-does-it-work/supporting-effective-professional-development/

**Comment by sarahlydic** [comment]
@ajp9e thank you! fixed
