### ISSUE TITLE
missing webinar

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#13]
Hi - I thought that I caught this and put it in github but maybe not?

https://aeiionline.org/advancing-effective-interactions-and-instruction-2/tools-resources/for-providing-feedback/

Doesn't link to webinar and missing image

![Screenshot_20200410-082159](https://user-images.githubusercontent.com/19825720/78998825-665c2300-7b17-11ea-9049-064bb24174d6.png)

**Comment by sarahlydic** [comment]
fixing

**Comment by sarahlydic** [comment]
fixed
