### ISSUE TITLE
AEII: Our Partners - change 'Early Adopters School Divisions' 

### ISSUE THREAD

**Issue by mrushfinn** [castl350/AEII#15]
Our Partners - bottom of the page
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/about-aeii/partners/

From Amanda:
the title for the school divisions still says “early adopter” school divisions and it needs to say 
“Virginia School Divisions”. The content under it was revised but the title was not.

**Comment by ajp9e** [comment]
Hi,

Thank you for this Miriam - I just entered this into github 🙂

Best,
A


________________________________
