### ISSUE TITLE
Missing quotation mark?

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#17]
Missing " on the impact page with the quote from the teacher (see below). Not sure if that's just how the graphic is, but wanted to double check.

https://aeiionline.org/advancing-effective-interactions-and-instruction-2/why-aeii/impact/
<img width="1194" alt="Screen Shot 2020-04-14 at 3 42 56 PM" src="https://user-images.githubusercontent.com/19825720/79267168-b2380080-7e66-11ea-9ea8-09ad7b0edafd.png">

**Comment by kneesen22** [comment]
that's how the graphic is..you just have an open quotation.
