### ISSUE TITLE
Map - incorrect content

### ISSUE THREAD

**Issue by mrushfinn** [castl350/AEII#18]
Site: Where is AEII?
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/about-aeii/where-is-aeii/

Map at the bottom states early and current incorrect adopter info. Comment: For instance, Bath, Lee, and New Kent Counties are all in the blue color, but we don't work with any of them. Those are the ones that stood out, though there might be others as well. Notify AEII, if need a corrected list of counties. 
Possible content change: delete the map.

**Comment by kneesen22** [comment]
Miriam checking with Amanda to see if we can take out.

**Comment by sarahlydic** [comment]
Sounds good. Grace approved these early adopters on 1/30, but happy to remove or replace map.

**Comment by sarahlydic** [comment]
Hi @mrushfinn I was curious about this and double-checked. Bath, Lee, and New Kent are in light blue, not dark blue. Per the caption, we worked with counties in dark blue. Not sure what you're seeing? Happy to delete/replace the map if needed but wasn't sure if we were looking at the same one? Thanks!

**Comment by mrushfinn** [comment]
@sarahlydic We can wait and see what Amanda says today. Allison told me they haven't worked at all with some of those counties.

**Comment by sarahlydic** [comment]
@mrushfinn Sounds good. Here's the list of early adopters as of 2/1/19 according to Grace & Ann (which is the same as the map) Just confirming that you're seeing the map in shades of blue with no orange? Thank you!
__
Accomack County Public Schools
Alleghany County Public Schools
Amherst County Public Schools
Augusta County
Bedford County Public Schools
Buckingham County
Caroline County Public Schools
Chesterfield County Public Schools
Clarke County Public Schools
Colonial Beach
Covington City
Essex
Fairfax County Office for Children
Floyd County
Franklin City Public Schools
Galax City Public Schools
Gloucester
Goochland County Schools
Grayson County
Hanover County Public Schools
Henrico County
Henry County Public Schools
Hopewell City Public Schools
Isle of Wight County Schools
Loudoun County Public Schools
Manassas City Public Schools
Mecklenburg
Montgomery County Public Schools
Newport News Public Schools
Northumberland County
Norton City Schools
Nottoway
Orange
Powhatan County Public Schools
Pulaski County
Radford City Public Schools
Roanoke City Public Schools
Roanoke County
Rockingham County Public Schools
Smyth County
Southampton County Public Schools
Spotsylvania
Staunton City
Suffolk Public Schools
Surry County Public Schools
Tazewell County Public Schools
Virginia Beach City Public Schools
Waynesboro Public Schools
Winchester City Public Schools
Wise County
York

**Comment by ajp9e** [comment]
Hi,

There are currently no early or current adopters - that is old terminology that we're not using any more.  To that end, I don't think that there should be any different colors. We work with ~123 divisions with the exception of a few that I would need to get verified most likely from VDOE maybe?

I really think that we wait until Amanda makes a call on this.

Best,


  1.  A

________________________________

**Comment by mrushfinn** [comment]
Hi all,
Per Amanda: please delete the map. 
Thanks!

**Comment by sarahlydic** [comment]
deleted. thanks!
