### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#2]
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/contact-us/

Probably shouldn't report this one as it is a copy issue so apologies if you already know about this one.
<img width="784" alt="Screen Shot 2020-04-02 at 12 33 55 PM" src="https://user-images.githubusercontent.com/19825720/78274510-583a5100-74de-11ea-8e4b-7551b34b9d37.png">

**Comment by sarahlydic** [comment]
Thank you! Just updated the text.
