### ISSUE TITLE
From the contact us page to ECE-Virginia top right 

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#3]
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/contact-us/

When I click on Early Childhood Education - Virginia I get this warning ... maybe something out of our control?
<img width="924" alt="Screen Shot 2020-04-02 at 12 36 34 PM" src="https://user-images.githubusercontent.com/19825720/78274748-a6e7eb00-74de-11ea-8b24-b76e32809319.png">

**Comment by mattsema** [comment]
addressed when New City fixed top navigation
