### ISSUE TITLE
From the contact us page ECE Virginia up top right 

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#4]
When I click on the Advancing Effective Interactions and Instruction AND the STREAMin3 I get this image 
<img width="1136" alt="Screen Shot 2020-04-02 at 12 38 07 PM" src="https://user-images.githubusercontent.com/19825720/78274973-fdedc000-74de-11ea-9bd1-97b3fe4394b8.png">

**Comment by kneesen22** [comment]
thanks. will submit ticket to New City
