### ISSUE TITLE
Link goes to wrong place

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#5]
At this link (​https://aeiionline.org/advancing-effective-interactions-and-instruction-2/tools-resources /for-use-in-professional-development/instructional-documents/​) all of the page links go to the wrong page starting from “Environment Rating Scales” through “Assessing and Scaffolding Make-Believe Play”

**Comment by sarahlydic** [comment]
@mattsema this is the resource library. I think you corrected, but can you confirm? Thanks!
https://aeiionline.org/advancing-effective-interactions-and-instruction-2/tools-resources/for-use-in-professional-development/instructional-documents/

**Comment by castl350** [comment]
links corrected
