### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#6]
This page (​https://aeiionline.org/advancing-effective-interactions-and-instruction-2/why-aeii/impa ct/​) seems to have a picture missing at the beginning.
   
<img width="1154" alt="Screen Shot 2020-04-03 at 10 01 36 AM" src="https://user-images.githubusercontent.com/19825720/78368775-25ea2b80-7592-11ea-8338-9c7b6bd17ec8.png">

**Comment by sarahlydic** [comment]
Thanks for catching! This was a placeholder. Deleted.
