### ISSUE TITLE
AEII who we are page

### ISSUE THREAD

**Issue by ajp9e** [castl350/AEII#7]
When Ann was reviewing the website she saw that Grace was still on this page and Ann would like "please update my picture to the one on my UVA profile"
![Screenshot_20200410-090356](https://user-images.githubusercontent.com/19825720/78997394-7c1c1900-7b14-11ea-9491-7e61b2fbc998.png)

**Comment by sarahlydic** [comment]
@ajp9e Thank you! Just noting that Ann's photo was her current Curry photo at the time of creating this page. I will replace. I'll also remove Grace -- just noting that it's a larger edit than simply deleting.

**Comment by sarahlydic** [comment]
updated
